name: Binary specific release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version that is going to be release'
        required: true
      new_version:
        description: 'The version that should be used as a new one after the release.'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ZOWE_ROBOT_TOKEN }}

      - uses: ./.github/actions/setup

      - name: Set up git
        run: |
          git config user.email "zowe-robot@users.noreply.github.com"
          git config user.name "Zowe Robot"

      - name: Release with Gradle
        run: >
          ./gradlew packageFilesApiServer release -Prelease.useAutomaticVersion=true
          -Prelease.releaseVersion=${{ github.event.inputs.release_version }}
          -Prelease.newVersion=${{ github.event.inputs.new_version }}
          -Pdeploy.username=$ARTIFACTORY_USERNAME -Pdeploy.password=$ARTIFACTORY_PASSWORD
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          BUILD_NUMBER: ${{ github.run_number }}
          BRANCH_NAME: ${{ github.ref_name }}

      - uses: ./.github/actions/teardown
