name: Binary specific release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version that is going to be release'
        required: true
      new_version:
        description: 'The version that should be used as a new one after the release.'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/setup

      - name: Release with Gradle
        run: >
          ./gradlew release -Prelease.useAutomaticVersion=true
          -Prelease.releaseVersion=${{ github.event.inputs.release_version }}
          -Prelease.newVersion=${{ github.event.inputs.new_version }}
          -Pdeploy.username=$ARTIFACTORY_USERNAME -Pdeploy.password=$ARTIFACTORY_PASSWORD
        env:
          ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - uses: ./.github/actions/teardown
