name: Image specific release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'The version that is going to be release'
        required: true

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: ./.github/actions/setup

      - name: Build with Gradle
        run: ./gradlew build

      - name: Unit test with Gradle
        run: ./gradlew coverage

      - uses: ./.github/actions/teardown

  PublishImages:
    needs: BuildAndTest
    uses: zowe/data-sets/.github/workflows/build-images.yml@v2.x/master
    with:
      versionOverride: ${{ github.event.inputs.release_version }}
    secrets:
      registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
      registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
      redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
      redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
      zlinux-host: ${{ secrets.ZLINUX_HOST }}
      zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
      zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
      zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}