name: Image snapshot release

on:
  push:
    branches:
      - master
      - v2.x/master

env:
  BRANCH_NAME: ${{ github.ref_name }}

jobs:
  publish-images:
    uses: zowe/data-sets/.github/workflows/build-images.yml@v2.x/master
    with:
      forceNoRelease: true
    secrets:
      registry-user: ${{ secrets.ARTIFACTORY_X_USERNAME }}
      registry-password: ${{ secrets.ARTIFACTORY_X_PASSWORD }}
      redhat-registry-user: ${{ secrets.REDHAT_DEVELOPER_USER }}
      redhat-registry-password: ${{ secrets.REDHAT_DEVELOPER_PASSWORD }}
      zlinux-host: ${{ secrets.ZLINUX_HOST }}
      zlinux-ssh-user: ${{ secrets.ZLINUX_SSH_USER }}
      zlinux-ssh-key: ${{ secrets.ZLINUX_SSH_KEY }}
      zlinux-ssh-passphrase: ${{ secrets.ZLINUX_SSH_PASSPHRASE }}